server:
  port: 8080
  servlet:
    context-path: /house

spring:
  profiles:
    active: mybatis
  freemarker:
    charset: utf-8
    content-type: text/html;charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: utf-8
      auto_import: common/common.ftl as common
file:
  path:
